### PR TITLE
Enhance docs

### PR DESCRIPTION
**Pull request by swethalohith2**
#What
 categorise the options and examples by test types

### CODE REVIEW

**Comment by rui1234** [comment]
See my comments


1. README:  "synctl create/update/delete cred - Manage credentials."  should be "synctl get/create/update/delete cred - Manage credentials."

2.  "--mark-synthetic-call" is available for Common, API Simple, API script, Webpage Simple, Browser Script, Webpage Script, but not for SSLCertificate, please check it in the docs

3. in Options for API Simple Tests of synctl-update-test.md and ynctl-patch-test.md,  there are no options for `--headers, --body, --expect-json,  --expect-match, --expect-exists, --expect-not-empty ...`


4. I think 2 options are confusing: 
in synctl-create-test.md
```
-f, --from-file <file>              Synthetic script, support js file, e.g, script.js
--from-json <json>                  full Synthetic test payload, support json file
```
in synctl-update-test.md and synctl-patch-test.md
```
 --file,-f <file-name>              json payload
 --script-file <file-name>          specify a script file to update APIScript or BrowserScript
```

`--file `and `--from-json` are the same and they are for all test types, right? If so, we need to just use one name "--from-json" and move it to "Common options"

`--from-file` and `--script-file`  are the same, right? If so, we need to just use one name, e.g` --script-file`.


5. in "Options for Webpage Script Tests" of synctl-update-test.md and ynctl-patch-test.md,  I do not see the option for specifying the selenium ide script.

and in "Examples for Webpage Script Tests"
```
# Update synthetic test with new script
synctl patch test <synthetic-id> --script-file new-api-script.js
```
This is wrong, Webpage script only accepts .side script, we can change the example to `synctl patch test <synthetic-id> --script-file seleniumide-script.side`

**Comment by rongzhus** [comment]
> See my comments
> 
>     1. README:  "synctl create/update/delete cred - Manage credentials."  should be "synctl get/create/update/delete cred - Manage credentials."
> 
>     2. "--mark-synthetic-call" is available for API Simple, API script, Webpage Simple, Browser Script, Webpage Script, but not for SSLCertificate, please check it in the docs
> 
>     3. in Options for API Simple Tests of synctl-update-test.md and ynctl-patch-test.md,  there are no options for `--headers, --body, --expect-json,  --expect-match, --expect-exists, --expect-not-empty ...`
> 
>     4. I think 2 options are confusing:
>        in synctl-create-test.md
> 
> 
> ```
> -f, --from-file <file>              Synthetic script, support js file, e.g, script.js
> --from-json <json>                  full Synthetic test payload, support json file
> ```
> 
> in synctl-update-test.md and synctl-patch-test.md
> 
> ```
>  --file,-f <file-name>              json payload
>  --script-file <file-name>          specify a script file to update APIScript or BrowserScript
> ```
> 
> `--file `and `--from-json` are the same and they are for all test types, right? If so, we need to just use one name "--from-json" and move it to "Common options"
> 
> `--from-file` and `--script-file` are the same, right? If so, we need to just use one name, e.g` --script-file`.
> 
>     5. in "Options for Webpage Script Tests" of synctl-update-test.md and ynctl-patch-test.md,  I do not see the option for specifying the selenium ide script.
> 
> 
> and in "Examples for Webpage Script Tests"
> 
> ```
> # Update synthetic test with new script
> synctl patch test <synthetic-id> --script-file new-api-script.js
> ```
> 
> This is wrong, Webpage script only accepts .side script, we can change the example to `synctl patch test <synthetic-id> --script-file seleniumide-script.side`

1. resolved. 
2 and 3 I will check and open an issue to add these missing parameters.
4. `-f` and `--from-json` and `--script-file` are different parameters, 
- `-f` is used to read script from file like js or side file. 
- `--from-json` is used to read a json file which is full json payload for Synthetic test
- `--script-file` is bundle entry file name. maybe `--entry-file` is better.
I will check and use same parameter in different command(update, create and patch), but this will cause incompatible issues with different versions.

5. resolved.

**Comment by rui1234** [comment]
> -f is used to read script from file like js or side file.
> --script-file is bundle entry file name. maybe --entry-file is better.

but in synctl-update-test.md, it says "-f" is used to read json,  "--script-file" is  to specify a script file and "--entry-file" is used to specify bundle entry file name

```
Options for Browser Script test
 --file,-f <file-name>              json payload
    --script-file <file-name>          specify a script file to update APIScript or BrowserScript
    --bundle <bundle>                  set bundle content
    --entry-file <string>              entry file of a bundle test
```

**Comment by rongzhus** [comment]
yes, now it use different options in create/update command, I will update the code to use same option.

**Comment by rongzhus** [comment]
For inconsistent options, will resolve it in another PR.

**Review by rongzhus — APPROVED** [review]

**Pull request merged**
